name: '🤯 Puzzle'
description: Why my awesome typescript doesnot work as expected
title: '[Puzzle]: '
labels: ['Puzzle']
body:
  - type: markdown
    attributes:
      value: |
        Please provide your puzzle with these steps:

         - Make sure you have googled or asked GPT and still have no idea.
         - Make sure you have already searched in issue of this repo and didn't find the same puzzle.
         - Provide link of [TypeScript Playground](https://www.typescriptlang.org/play/).
         - Provide key informations like, how should it works, what's the expected result, what's the actual result, etc.
